CREATE TABLE IF NOT EXISTS `#__zqj30_zqj30coms` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Automatic incre-menting key field',
  `catid` int(11) NOT NULL DEFAULT '0' COMMENT 'Foreign key to #__categories table',
  `title` varchar(250) NOT NULL DEFAULT '' COMMENT 'Title',
  `alias` varchar(255) NOT NULL DEFAULT '' COMMENT 'Alias value, used for SEF URLs',
  `description` text NOT NULL COMMENT 'Description (will be edited using editor)',
  `state` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Published state (1=published, 0=unpublished, -2=trashed)',
  `ordering` int(11) NOT NULL DEFAULT '0' COMMENT 'Optionally used to order items',
  `checked_out` int(11) NOT NULL DEFAULT '0' COMMENT 'Foreign key to #__users table for user who checked out this item',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Time item checked out',
  `access` int(11) NOT NULL DEFAULT '1' COMMENT 'Used to control access to items',
  `language` char(7) NOT NULL DEFAULT '' COMMENT 'For possible future use to add language switching',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Datetime this item was created',
  `created_by` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Foreign key to #__users table for user who created this item',
  `created_by_alias` varchar(255) NOT NULL DEFAULT '' COMMENT 'Alias for the user who created this item',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Datetime this item was last modified',
  `modified_by` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Foreign key to #__users table for user who modified this item',
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Date to start publishing this item',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Date to stop publishing this item',
  `params` text NOT NULL COMMENT 'Item level parameters (JSON string format)',
  PRIMARY KEY (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_state` (`state`),
  KEY `idx_catid` (`catid`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_language` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;